# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import web_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=100, verbose_name='address_line')),
                ('county', models.CharField(max_length=50, verbose_name='country')),
                ('postcode', models.CharField(max_length=10, verbose_name='postcode')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('surname', models.CharField(max_length=30, verbose_name='surname')),
                ('telephone', models.CharField(max_length=15, verbose_name='telephone')),
                ('mobile', models.CharField(max_length=15, verbose_name='mobile')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to=web_app.models.get_logo_file_name)),
                ('description', models.TextField(verbose_name='description')),
                ('just_giving_link', models.URLField(blank=True, max_length=255, verbose_name='just giving link')),
                ('raised', models.DecimalField(blank=True, decimal_places=2, max_digits=25, verbose_name='raised')),
                ('goal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, verbose_name='goal')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.Address')),
                ('primary_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.Contact')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('end_time', models.DateTimeField(verbose_name='end_time')),
                ('reoccurring', models.BooleanField(verbose_name='reoccurring')),
                ('items', models.ManyToManyField(to='web_app.Item')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='wishlist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.Wishlist'),
        ),
    ]
