# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_organisation_just_giving_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='goal',
            field=models.CharField(blank=True, max_length=10, verbose_name='goal'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='raised',
            field=models.CharField(blank=True, max_length=10, verbose_name='raised'),
        ),
    ]
