# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20161005_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('occupation', models.CharField(max_length=30, verbose_name='occupation')),
                ('about_me', models.CharField(max_length=300, verbose_name='about me')),
                ('experience', models.CharField(max_length=300, verbose_name='experience')),
                ('training', models.CharField(max_length=100, verbose_name='training')),
                ('facebook_link', models.URLField(blank=True, max_length=255, verbose_name='facebook link')),
                ('twitter_link', models.URLField(blank=True, max_length=255, verbose_name='twitter link')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
            ],
        ),
    ]
