# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20161004_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(default='belfast', max_length=50, verbose_name='county'),
            preserve_default=False,
        ),
    ]
