# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20160910_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='item',
            name='wishlists',
            field=models.ManyToManyField(to='web_app.Wishlist'),
        ),
    ]
