# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='about_me',
            field=models.CharField(max_length=300, verbose_name='about_me'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='facebook_link'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='twitter_link'),
        ),
    ]
