# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import web_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20161015_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default='setme', max_length=30, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=web_app.models.get_volunteer_profile_picture_path),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='surname',
            field=models.CharField(default='setme', max_length=30, verbose_name='surname'),
            preserve_default=False,
        ),
    ]
