# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-22 22:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20161015_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0, 'Goal cannot be negative')], verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='raised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0, 'Raised cannot be negative')], verbose_name='raised'),
        ),
    ]
